list_currency = (
    ("usd", "US Dollar"),
    ("idr", "Indonesian Rupiah"),
    ("twd", "New Taiwan Dollar"),
    ("eur", "Euro"),
    ("krw", "South Korean Won"),
    ("jpy", "Japanese Yen"),
    ("rub", "Russian Ruble"),
    ("cny", "Chinese Yuan"),
    ("aed", "United Arab Emirates Dirham"),
    ("ars", "Argentine Peso"),
    ("aud", "Australian Dollar"),
    ("bdt", "Bangladeshi Taka"),
    ("bhd", "Bahraini Dinar"),
    ("bmd", "Bermudian Dollar"),
    ("brl", "Brazil Real"),
    ("cad", "Canadian Dollar"),
    ("chf", "Swiss Franc"),
    ("clp", "Chilean Peso"),
    ("czk", "Czech Koruna"),
    ("dkk", "Danish Krone"),
    ("gbr", "British Pound Sterling"),
    ("hkd", "Hong Kong Dollar"),
    ("huf", "Hungarian Forint"),
    ("ils", "Israeli New Shekel"),
    ("inr", "Indian Rupee"),
    ("kwd", "Kuwaiti Dinar"),
    ("lkr", "Sri Lankan Rupee"),
    ("mmk", "Burmese Kyat"),
    ("mxn", "Mexican Peso"),
    ("myr", "Malaysian Ringgit"),
    ("ngn", "Nigerian Naira"),
    ("nok", "Norwegian Krone"),
    ("nzd", "New Zealand Dollar"),
    ("php", "Philippine Peso"),
    ("pkr", "Pakistani Rupee"),
    ("pln", "Polish Zloty"),
    ("sar", "Saudi Riyal"),
    ("sek", "Swedish Krona"),
    ("sgd", "Singapore Dollar"),
    ("thb", "Thai Baht"),
    ("try", "Turkish Lira"),
    ("uah", "Ukrainian hryvnia"),
    ("vef", "Venezuelan bolívar fuerte"),
    ("vnd", "Vietnamese đồng"),
    ("zar", "South African Rand"),
    ("xdr", "IMF Special Drawing Rights"),
)
