# Generated by Django 3.1.7 on 2021-03-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_invoice",
                    models.CharField(
                        max_length=19, unique=True, verbose_name="Номер счета"
                    ),
                ),
                ("name_coin", models.CharField(max_length=100, verbose_name="Монета")),
                ("vs_currency", models.CharField(max_length=50, verbose_name="Валюта")),
                ("current_price", models.FloatField(verbose_name="Цена")),
                ("amount", models.IntegerField(default=1, verbose_name="Количество")),
                ("total", models.FloatField(verbose_name="Сумма")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-number_invoice",),
            },
        ),
    ]
